 // Mobile Navigation
         const hamburger = document.querySelector('.hamburger');
                 const navLinks = document.querySelector('.nav-links');
                         
                                 hamburger.addEventListener('click', () => {
                                             navLinks.classList.toggle('active');
                                                     });
                                                             
                                                                     // Close mobile menu when clicking a link
                                                                             document.querySelectorAll('.nav-links a').forEach(link => {
                                                                                         link.addEventListener('click', () => {
                                                                                                         navLinks.classList.remove('active');
                                                                                                                     });
                                                                                                                             });
                                                                                                                                     
                                                                                                                                             // Accordion functionality
                                                                                                                                                     const accordionItems = document.querySelectorAll('.accordion-item');
                                                                                                                                                             
                                                                                                                                                                     accordionItems.forEach(item => {
                                                                                                                                                                                 const header = item.querySelector('.accordion-header');
                                                                                                                                                                                             
                                                                                                                                                                                                         header.addEventListener('click', () => {
                                                                                                                                                                                                                         const currentlyActive = document.querySelector('.accordion-item.active');
                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                         // Close other open items
                                                                                                                                                                                                                                                                         if(currentlyActive && currentlyActive !== item) {
                                                                                                                                                                                                                                                                                             currentlyActive.classList.remove('active');
                                                                                                                                                                                                                                                                                                                 currentlyActive.querySelector('.accordion-header i').className = 'fas fa-plus';
                                                                                                                                                                                                                                                                                                                                 }
                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                 // Toggle current item
                                                                                                                                                                                                                                                                                                                                                                                 item.classList.toggle('active');
                                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                 const icon = header.querySelector('i');
                                                                                                                                                                                                                                                                                                                                                                                                                                 icon.className = item.classList.contains('active') ? 'fas fa-minus' : 'fas fa-plus';
                                                                                                                                                                                                                                                                                                                                                                                                                                             });
                                                                                                                                                                                                                                                                                                                                                                                                                                                     });
                                                                                                                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                                                                                                     // Smooth scrolling for anchor links
                                                                                                                                                                                                                                                                                                                                                                                                                                                                             document.querySelectorAll('a[href^="#"]').forEach(anchor => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         anchor.addEventListener('click', function(e) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         e.preventDefault();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         const targetId = this.getAttribute('href');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         const targetElement = document.querySelector(targetId);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         if (targetElement) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             window.scrollTo({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     top: targetElement.offsetTop - 80,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             behavior: 'smooth'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     });