  // Mobile Navigation
          const hamburger = document.querySelector('.hamburger');
                  const navLinks = document.querySelector('.nav-links');
                          
                                  hamburger.addEventListener('click', () => {
                                              navLinks.classList.toggle('active');
                                                      });
                                                              
                                                                      // Close mobile menu when clicking a link
                                                                              document.querySelectorAll('.nav-links a').forEach(link => {
                                                                                          link.addEventListener('click', () => {
                                                                                                          navLinks.classList.remove('active');
                                                                                                                      });
                                                                                                                              });
                                                                                                                                      
                                                                                                                                              // Tab functionality
                                                                                                                                                      const tabBtns = document.querySelectorAll('.tab-btn');
                                                                                                                                                              const tabContents = document.querySelectorAll('.tab-content');
                                                                                                                                                                      
                                                                                                                                                                              tabBtns.forEach(btn => {
                                                                                                                                                                                          btn.addEventListener('click', () => {
                                                                                                                                                                                                          const tabId = btn.getAttribute('data-tab');
                                                                                                                                                                                                                          
                                                                                                                                                                                                                                          // Remove active class from all buttons and contents
                                                                                                                                                                                                                                                          tabBtns.forEach(btn => btn.classList.remove('active'));
                                                                                                                                                                                                                                                                          tabContents.forEach(content => content.classList.remove('active'));
                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                          // Add active class to clicked button and corresponding content
                                                                                                                                                                                                                                                                                                                          btn.classList.add('active');
                                                                                                                                                                                                                                                                                                                                          document.getElementById(tabId).classList.add('active');
                                                                                                                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                              // FAQ functionality
                                                                                                                                                                                                                                                                                                                                                                                      const faqItems = document.querySelectorAll('.faq-item');
                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                      faqItems.forEach(item => {
                                                                                                                                                                                                                                                                                                                                                                                                                  const question = item.querySelector('.faq-question');
                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                          question.addEventListener('click', () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                          const currentlyActive = document.querySelector('.faq-item.active');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          // Close other open items
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if(currentlyActive && currentlyActive !== item) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              currentlyActive.classList.remove('active');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  currentlyActive.querySelector('.faq-question i').className = 'fas fa-plus';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // Toggle current item
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  item.classList.toggle('active');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const icon = question.querySelector('i');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  icon.className = item.classList.contains('active') ? 'fas fa-minus' : 'fas fa-plus';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      // Smooth scrolling for anchor links
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              document.querySelectorAll('a[href^="#"]').forEach(anchor => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          anchor.addEventListener('click', function(e) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          e.preventDefault();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const targetId = this.getAttribute('href');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const targetElement = document.querySelector(targetId);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if (targetElement) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              window.scrollTo({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      top: targetElement.offsetTop - 80,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              behavior: 'smooth'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      });